git:
  submodules: true
language: scala
# run on new infrastructure
sudo: false

script:
  - cd dsp-framework; echo "Publishing the framework, this may take a while..."; ./update.bash > /dev/null; cd ..; echo "Done updating!"
  - sbt travis:test

